#!/bin/bash
die() { echo $1; exit 1; }
git checkout master && git pull || die "failed to pull main repo"
[ -e 'externals' ] || mkdir externals
cd externals
echo 'riscoss-risk-modeling
riscoss-data-collector
riscoss-analyser' | while read repo
do
    [ -e "./${repo}/.git" ] || rm -rf "./${repo}/" 2>/dev/null;
    [ -e "./${repo}/" ] || git clone "git://github.com/riscoss/${repo}.git";
    ( cd "${repo}" && git pull || die "failed to pull ${repo} subrepo" )
done
